;;; reddigg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from reddigg.el

(autoload 'reddigg-view-comments "reddigg" "\
Ask and print CMT to buffer.

(fn CMT)" t)
(autoload 'reddigg-view-sub "reddigg" "\
Prompt SUB and print its post list.

(fn SUB)" t)
(autoload 'reddigg-view-frontpage "reddigg" "\
View frontpage." t)
(autoload 'reddigg-view-main "reddigg" "\
View main page." t)
(register-definition-prefixes "reddigg" '("reddigg-"))

;;; End of scraped data

(provide 'reddigg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; reddigg-autoloads.el ends here
